language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - gulp build
  - gulp test